[project]
name = "whats-hard-llm-powered-apps"
version = "0.1.0"
description = ""
authors = [{ name = "Ian Massingham", email = "ian@griptape.ai" }]
requires-python = "~=3.12"
readme = "README.md"
dependencies = [
    "python-dotenv>=1.0.1,<2",
    "griptape[all]>=1.3.3,<2",
]
c